//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.17 at 10:26:17 PM IDT 
//


package meirdev.cpu.simeasy8.processor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CpuOperands"/>
 *         &lt;element ref="{}CpuRegisters"/>
 *         &lt;element ref="{}CpuInstructionList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cpuOperands",
    "cpuRegisters",
    "cpuInstructionList"
})
@XmlRootElement(name = "Cpu")
public class Cpu {

    @XmlElement(name = "CpuOperands", required = true)
    protected CpuOperands cpuOperands;
    @XmlElement(name = "CpuRegisters", required = true)
    protected CpuRegisters cpuRegisters;
    @XmlElement(name = "CpuInstructionList", required = true)
    protected CpuInstructionList cpuInstructionList;

    /**
     * Gets the value of the cpuOperands property.
     * 
     * @return
     *     possible object is
     *     {@link CpuOperands }
     *     
     */
    public CpuOperands getCpuOperands() {
        return cpuOperands;
    }

    /**
     * Sets the value of the cpuOperands property.
     * 
     * @param value
     *     allowed object is
     *     {@link CpuOperands }
     *     
     */
    public void setCpuOperands(CpuOperands value) {
        this.cpuOperands = value;
    }

    /**
     * Gets the value of the cpuRegisters property.
     * 
     * @return
     *     possible object is
     *     {@link CpuRegisters }
     *     
     */
    public CpuRegisters getCpuRegisters() {
        return cpuRegisters;
    }

    /**
     * Sets the value of the cpuRegisters property.
     * 
     * @param value
     *     allowed object is
     *     {@link CpuRegisters }
     *     
     */
    public void setCpuRegisters(CpuRegisters value) {
        this.cpuRegisters = value;
    }

    /**
     * Gets the value of the cpuInstructionList property.
     * 
     * @return
     *     possible object is
     *     {@link CpuInstructionList }
     *     
     */
    public CpuInstructionList getCpuInstructionList() {
        return cpuInstructionList;
    }

    /**
     * Sets the value of the cpuInstructionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CpuInstructionList }
     *     
     */
    public void setCpuInstructionList(CpuInstructionList value) {
        this.cpuInstructionList = value;
    }

}
