//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.17 at 10:26:17 PM IDT 
//


package meirdev.cpu.simeasy8.processor;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the meirdev.cpu.simeasy8.processor package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OperandName_QNAME = new QName("", "OperandName");
    private final static QName _CpuRegister_QNAME = new QName("", "CpuRegister");
    private final static QName _InstructioName_QNAME = new QName("", "instructioName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: meirdev.cpu.simeasy8.processor
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cpu }
     * 
     */
    public Cpu createCpu() {
        return new Cpu();
    }

    /**
     * Create an instance of {@link CpuOperands }
     * 
     */
    public CpuOperands createCpuOperands() {
        return new CpuOperands();
    }

    /**
     * Create an instance of {@link CpuRegisters }
     * 
     */
    public CpuRegisters createCpuRegisters() {
        return new CpuRegisters();
    }

    /**
     * Create an instance of {@link CpuInstructionList }
     * 
     */
    public CpuInstructionList createCpuInstructionList() {
        return new CpuInstructionList();
    }

    /**
     * Create an instance of {@link Instruction }
     * 
     */
    public Instruction createInstruction() {
        return new Instruction();
    }

    /**
     * Create an instance of {@link OperationList }
     * 
     */
    public OperationList createOperationList() {
        return new OperationList();
    }

    /**
     * Create an instance of {@link OperationCode }
     * 
     */
    public OperationCode createOperationCode() {
        return new OperationCode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OperandName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOperandName(String value) {
        return new JAXBElement<String>(_OperandName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CpuRegister")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCpuRegister(String value) {
        return new JAXBElement<String>(_CpuRegister_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "instructioName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInstructioName(String value) {
        return new JAXBElement<String>(_InstructioName_QNAME, String.class, null, value);
    }

}
