//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 12:23:00 PM IDT 
//


package meirdev.cpu.simeasy8.processor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}instructioName"/>
 *         &lt;element ref="{}OperationList"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ov" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "instructioName",
    "operationList"
})
@XmlRootElement(name = "Instruction")
public class Instruction {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String instructioName;
    @XmlElement(name = "OperationList", required = true)
    protected OperationList operationList;
    @XmlAttribute(name = "ov", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ov;
    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String type;

    /**
     * Gets the value of the instructioName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstructioName() {
        return instructioName;
    }

    /**
     * Sets the value of the instructioName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstructioName(String value) {
        this.instructioName = value;
    }

    /**
     * Gets the value of the operationList property.
     * 
     * @return
     *     possible object is
     *     {@link OperationList }
     *     
     */
    public OperationList getOperationList() {
        return operationList;
    }

    /**
     * Sets the value of the operationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationList }
     *     
     */
    public void setOperationList(OperationList value) {
        this.operationList = value;
    }

    /**
     * Gets the value of the ov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOv() {
        return ov;
    }

    /**
     * Sets the value of the ov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOv(String value) {
        this.ov = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
